name:                pico
version:             0.1.0.0
github:              "yang-zhu/pico"
license:             BSD3
author:              "Zhu Yang"
copyright:           "2022 Zhu Yang"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/yang-zhu/pico#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- random

library:
  source-dirs: src

default-extensions:
- BlockArguments
- LambdaCase
- NamedFieldPuns
- InstanceSigs
- ScopedTypeVariables
